

### Press Esc to enter Command Mode before using these:
### A: Insert new cell Above.
### 
### B: Insert new cell Below.
### 
### D, D (Press D twice): Delete the current cell.
### 
### Z: Undo a cell deletion (lifesaver!).
### 
### M: Change cell to Markdown (for notes/headings).
### 
### Y: Change cell back to Code.
### 
### L: Toggle Line Numbers (very helpful when debugging NumPy errors).

# Numpy

### Numpy is a Fundamental Package for scientific computing in python. Its a python library that provides a Multi Dimensional Array object and variours derived object such as masked arrays or matrices and an assortment of routines for fast operations on Arrays including mathematical, logical, shape manipulation, selecting , I/o , Discrete fourier Tranform, Basic linear algebra, Stastical operation , random simulation , etc.

### At the core of the numpy package in the ndimensional array object


## why numpy?
### list, dict --> quite slow for data science
###  syntax python was easy compared to c/ java those were fast 
### mathematician finds its easy so use it for data science

### we needed and less memory to work wih huge amount of data.

### so using numpy provide speed required for these scientific calculation along with  that data matrices created through numpy used less memory


### numpy --> c language --> wrapped ---> python language
### so NumPy is written in C (and C++) and provides a Python interface, which makes operations fast.

### numpy syntax easy for beginner -->performing scientific calcaultion---> careating multidimensional arrays---> speed is faster for applying operations---> less memory


### base of pandas is numpy as dealing with csv in pandas has numerical columns and these numerical data is being processed in the form of a numpy array itself . so we used numpy array to store that column in form of numrical array itself


### In matplotlib also using sin function you need to used functionality of numpy lib i.e sin function


### lib like scikit learn , tensorflow , and pytorch req input data in numpy arrays  or tensors.

## Numpy arrays vs python sequences

### Numpy arrays have a fixed size at creation unlike python list which grows dynamically.

### Changing size of ndim array(numpy array) will create new one and del old one

### The elem in a numpy are req to be of same data type and thus will be of same of same size in memory

### numpy arrays facilitate advanced mathematical and other types of opertions on large number of data . typically such operation are excecuted more efficiently with less code than is possible using python's built in sequence. e.g applying fourier tranform quite difficult on raw python as applying all that operation from scatch code by code is difficult but numpy you dont need to do it has all that functionalties just call them.

## why numpy is faster ?
### Vectorization (no Python loops) 
### Contiguous memory storage
### SIMD optimizations (low-level)

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


## np.array()--> creating multidimensional array


In [3]:
numpy_array = np.array([1,2,3,4,False]) #vector

In [4]:
numpy_array

array([1, 2, 3, 4, 0])

In [5]:
type(numpy_array)

numpy.ndarray

In [6]:
twoDArray= np.array([[1,2,3],[4,5,6],[7,8,9]])  # twoDArray is matrix

In [7]:
twoDArray # one block three rows three columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Note : In 2d,3d, Numpy arrays must have same shape per dimension level (regular structure), not just “same number of columns”.

In [8]:
threeDarray =  np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) # Tensor

In [9]:
threeDarray # three block , in each block 2 rows 2 columns

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

#### dtype parameter --> which can help us out  with deciding about the size of the data we are going to store inside our array

In [10]:
np.array([1,2,3,4,5], dtype =np.int32)

array([1, 2, 3, 4, 5], dtype=int32)

In [11]:
np.array([6,7,8,9,10], dtype =np.int64)

array([ 6,  7,  8,  9, 10])

In [12]:
#similarly np.float32/64

In [13]:
np.array([1,2,3,4,5],dtype=float)

array([1., 2., 3., 4., 5.])

In [14]:
np.array([1,2,3,4,False],dtype=bool)

array([ True,  True,  True,  True, False])

## arange() --> It help us provind the values over a certain range.same like range but less code.


In [123]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [16]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [307]:
arange_data = np.arange(1,17)

In [20]:
arange_data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### np.reshape --> helps out changing the shape of array as per out need

In [316]:
# convert 1D to 2D array
arange_data_2d=arange_data.reshape(8,2)
print(arange_data_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
# convert 2d array to 1d array 
arange_data_2d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [28]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### np.ones() ---> use to Initialze the weight of the neurons in the neural network. In TensorFlow , It uses tensors, which are generalizations of NumPy arrays (can be 1D, 2D, 3D, or higher).Though better way is np.random.random((3, 4)) becoz here weight something new

In [34]:
#similar like
print(np.zeros((3,4)))
print()
print(np.zeros((3,4),dtype=int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# random() ---> it  helps us out generating any random values from 0 to 1 inside our matrix.

## Also

## np.random.randint()
## np.random.randn()
## np.random.seed()

In [36]:
np.random.random((3,4))

array([[0.83604967, 0.06243526, 0.97737735, 0.34608379],
       [0.318875  , 0.42992612, 0.51773924, 0.66198685],
       [0.97494271, 0.11163741, 0.2254673 , 0.80193091]])

### Identity() --> it helps us out with creating the matrix as an identity matrix( Square matrix ---> Rows = column)

In [317]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### linespace()  it make sure every value with the givern range is going to have similar distance from each other.

##

In [45]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## Attributes

In [ ]:
# ndim -->  ndim stands for n dimension

In [47]:
arr = np.array([1,2,3])

In [48]:
arr

array([1, 2, 3])

In [49]:
arr.ndim

1

In [56]:
arrray = np.array([[[1,2],[10,11]],[[3,4],[11,12]],[[5,6],[13,14]]])

In [57]:
arrray

array([[[ 1,  2],
        [10, 11]],

       [[ 3,  4],
        [11, 12]],

       [[ 5,  6],
        [13, 14]]])

In [58]:
arrray.ndim

3

### shape attribute --> it provides with the idea about the row and columns in our dataset

##

In [62]:
aRRay = np.array([[1,3,5],[2,3,5]])
print(aRRay)

[[1 3 5]
 [2 3 5]]


In [ ]:
aRRay.shape

(2, 3)

In [64]:
# find shape 3d array
print(np.array([[[1,2],[10,11]],[[3,4],[11,12]],[[5,6],[13,14]]]))
np.array([[[1,2],[10,11]],[[3,4],[11,12]],[[5,6],[13,14]]]).shape

[[[ 1  2]
  [10 11]]

 [[ 3  4]
  [11 12]]

 [[ 5  6]
  [13 14]]]


(3, 2, 2)

In [65]:
np.array([1,2]).shape

(2,)

### Note in above 2 example shape returns as follows

#### 1D: (columns,)
#### 2D: (rows, columns)
#### 3D: (depth/stacks, rows, columns)


## size --> total n`o. of elem present inside our dataset 
## and itemsize --> provide  size of  a unique elem inside our array in bytes

In [68]:
np.arange(2,52).size

50

In [ ]:
np.array([[1,3,5],[2,3,5]]).itemsize # by default is int64 so each int size is 8 bytes

8

In [ ]:
np.array([[1,3,5],[2,3,5]], dtype= np.int32).itemsize # we provide int32 so each int size 4

4

### dtype --> it provides us with the idea about the type of every item inside our array

In [74]:
np.array([[1,3,5],[2,3,'hi']]).dtype

dtype('<U21')

#### Note : NumPy arrays must have a single data type (homogeneous).
#### But your array contains:
#
##### Integers → 1, 3, 5, 2, 3
##### 
##### A string → 'hi'
##### 
#### 👉 NumPy automatically upcasts everything to a common type that can hold all values.
#### i.e array([['1', '3', '5'],['2', '3', 'hi']], dtype='<U21')
### If even ONE element is a string → whole array becomes string

### astype --> it helps us out to figure out the data type of the column in the dataset in pandas and it will be used in numpy as well to convert data type, not to check it.

In [321]:
array = np.arange(1,10).reshape(3,3)

In [322]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [323]:
array = array.astype('float64')
print(array)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [324]:
array.dtype

dtype('float64')

In [325]:
print(np.random.random((3,3)))

[[0.93928493 0.00566737 0.6664907 ]
 [0.66627381 0.25889429 0.00345206]
 [0.45617302 0.81562045 0.54179127]]


In [326]:
array = np.random.random((3,3))*100
print(array)

[[13.43150086 37.55935376 27.83670029]
 [27.50503146 26.3206672  44.80011018]
 [19.9112588  63.68051198 98.70959476]]


In [327]:
np.round(array)

array([[13., 38., 28.],
       [28., 26., 45.],
       [20., 64., 99.]])

In [328]:
array =array.astype('int32')

## LEC-3 Mathematical operations in numpy

In [ ]:
## Scaler operations -->  A scalar value operations will be done with the array or numeric value (e.g 1,4)  

In [329]:
print(array)
array = array+2


[[13 37 27]
 [27 26 44]
 [19 63 98]]


In [330]:
array

array([[ 15,  39,  29],
       [ 29,  28,  46],
       [ 21,  65, 100]], dtype=int32)

In [349]:
# Note --> Broadcasting 
arr = np.array([1,2,3])
print(arr + 10,end='\n\n')

# Also
a = np.array([[1],[2],[3]]) # 2D array with three rows
b = np.array([10,20,30]) # 1D array , so each 1d array elem add up top 2d array --> final 2d array
print(a + b)

[11 12 13]

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [101]:
array = array -10

In [102]:
array

array([[58, 40, 16],
       [55, 67, 30],
       [25, 21, 41]], dtype=int32)

In [103]:
array*=2

In [104]:
array

array([[116,  80,  32],
       [110, 134,  60],
       [ 50,  42,  82]], dtype=int32)

In [105]:
array/2

array([[58., 40., 16.],
       [55., 67., 30.],
       [25., 21., 41.]])

In [106]:
#  We can apply scalar operation with array in terms of arithmetic operations

In [109]:
print(array)


[[116  80  32]
 [110 134  60]
 [ 50  42  82]]


In [110]:
array>60

array([[ True,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [111]:
## Vector Operations ---> operations will be in btw the given no. of matrices

In [112]:
arr_1 = np.arange(1,17).reshape(4,4)

In [113]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [134]:
arr_2 = np.arange(17,33).reshape(4,4)

In [136]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [137]:
arr_1+arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [138]:
arr_2-arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [139]:
arr_2*arr_1

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [140]:
### Important Functions in Numpy for Machine learning and Data science

In [141]:
# max , min

In [144]:
print(arr_1)
np.max(arr_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


np.int64(16)

In [147]:
# row and column wise max and min
np.max(arr_1,axis=0) # column wise

array([13, 14, 15, 16])

In [149]:
np.max(arr_1,axis=1) # row wise

array([ 4,  8, 12, 16])

In [ ]:
# sum() ---> calulate the sum of all of the values of a given matrix
# syntax ---> np.sum()


In [151]:
np.sum(arr_1)

np.int64(136)

In [ ]:
print(np.sum(arr_1,axis=0)) # sum of values column wise 
print(np.sum(arr_1,axis=1)) # sum of values row wise 

[28 32 36 40]
[10 26 42 58]


In [154]:
# Same like sum , is product function
np.prod(arr_1)

np.int64(20922789888000)

In [156]:
print(arr_1)
np.prod(arr_1,axis =1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([   24,  1680, 11880, 43680])

## Statistical function in numpy

In [318]:
# mean() --> np.mean

In [158]:
np.mean(arr_1)

np.float64(8.5)

In [163]:
print(arr_1)
print(np.mean(arr_1,axis =1))
print(np.mean(arr_1,axis =0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2.5  6.5 10.5 14.5]
[ 7.  8.  9. 10.]


In [ ]:
np.std(arr_1) # again you can pass for axis = 0 and axis = 1 

np.float64(4.6097722286464435)

In [167]:
# median() --> calculare median  of all values in matrix or array
np.median(arr_1) # same goes for axis =0 and axis =1


np.float64(8.5)

In [168]:
# var  

In [170]:
np.var(arr_1) # same goes of row and column wise

np.float64(21.25)

In [171]:
#  sin/cos/tan np.sin(0/45/60/12 ) 

## dot product --> condition columns of first matrix must equal to rows of second matrix--> np.dot

# Also

### @ operator
### np.matmul()

In [181]:
matrix_1 = np.round(np.random.random((3,4))*100).astype('int32')
matrix_2 = np.round(np.random.random((4,3))*100).astype('int32')
print(matrix_1,end='\n\n')
print(matrix_2)
np.dot(matrix_1,matrix_2)

[[16 45 37 12]
 [24 31 43 80]
 [48 56 51 75]]

[[14 78 96]
 [14 72  4]
 [76 86 62]
 [ 4 37 57]]


array([[ 3714,  8114,  4694],
       [ 4358, 10762,  9654],
       [ 5632, 14937, 12269]], dtype=int32)

In [182]:
#log , exp of each and every single value of matrix value 

In [184]:
print(np.log(arr_1))
print()
print(np.exp(arr_1))

[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]
 [4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06]]


In [ ]:
## round() --> rounding off float values to its nearest possible integer value --> np.round()
## i.e 1.7--> 2 , 1.3 --> 1

## ceil() -->  Next corresponding value -->  np.ceil()
# 1.6 ---> 2 , 1.3--> 2
 
## floor() --> Provide previous value --> np.floor()
#  1.6 --> 1, 1.3 --> 1

In [193]:
array = np.random.random((3,4))*10
print(array)

[[1.78840298 0.3930398  8.92389607 2.98801742]
 [3.95787728 5.15992077 5.28834206 6.916279  ]
 [2.20244181 7.61404123 6.48045884 0.60146811]]


In [197]:
print(np.ceil(array))
print()
print(np.floor(array))

[[2. 1. 9. 3.]
 [4. 6. 6. 7.]
 [3. 8. 7. 1.]]

[[1. 0. 8. 2.]
 [3. 5. 5. 6.]
 [2. 7. 6. 0.]]


In [ ]:
# Transpose --> np.transpose(arr) or arr.T
# (i,j) --> (j,i) ---> (3,4) --> (4,3)

In [199]:
array = np.arange(1,17).reshape(4,4)

In [200]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [201]:
array.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [ ]:
## Ravel()  --> Ravel() --> np.ravel() --> convert nd array to 1d array
## or array.reshape(-1)
# or flatten() 

In [203]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.ndim(array) 
#or
array.ndim

2

In [208]:
np.ravel(array) 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [209]:
# Note 
'''
| Method      | Copy or View  |
| ----------- | ------------- |
| `reshape()` | view (mostly) |
| `ravel()`   | view          |
| `flatten()` | copy          |

'''

'''
Copy vs View (simple meaning)

🟢 1. View → same data (shared memory)
A view does NOT create new data
It just gives another way to look at the same array
👉 If you change one → the other also changes

e,g
import numpy as np
arr = np.array([1, 2, 3])
view_arr = arr.reshape(-1)   # usually a view

view_arr[0] = 100

print(arr)       # 🔥 changed!
print(view_arr)
'''


'''
2. Copy → separate data
A copy creates new memory
Changes do NOT affect original array

e.g of copy -->
arr = np.array([1, 2, 3])
copy_arr = arr.flatten()   # copy

copy_arr[0] = 100

print(arr)       # ❌ unchanged
print(copy_arr)
'''

'\n2. Copy → separate data\nA copy creates new memory\nChanges do NOT affect original array\n\ne.g of copy -->\narr = np.array([1, 2, 3])\ncopy_arr = arr.flatten()   # copy\n\ncopy_arr[0] = 100\n\nprint(arr)       # ❌ unchanged\nprint(copy_arr)\n'

In [220]:
# Indexing and slicing in Numpy --> same like list
# 1D array 
print(arange_data)
print(arange_data[0])

# 2D array
print(array)
print(array[0,2]) # array[0][2] i.e array_name[row][column]

# 3D array
print(arrray)
print(arrray[2][0][1]) # array_name[block, row, column] or array_name[z-axis, x-axis, y-axis]

[17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
17
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
3
[[[ 1  2]
  [10 11]]

 [[ 3  4]
  [11 12]]

 [[ 5  6]
  [13 14]]]
6


In [222]:
array_3d = np.arange(1,9).reshape(2,2,2)

In [223]:
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [224]:
array_3d[1,0,1]

np.int64(6)

In [ ]:
# one more concept --> Boolean indexing
arr = np.array([1,2,3,4])
# as arr > 2 result is array([False, False,  True,  True])
arr[([False, False,  True,  True])] 


array([3, 4])

In [ ]:
# Fancy indexing
arr[[0,2,3]]

array([1, 3, 4])

In [226]:
# slicing ---> similar approach just like the list [:]
# 2D Array --> [row_1:row_2, col_1:col_2]

In [227]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
array[:,3] # all rows and column 3 --> so we get all values of column 3

array([ 4,  8, 12, 16])

In [229]:
array[2:4,:] # row 2 and 3 , column all --> so we get row 2 and row 3 all values

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
array[1,1:3] # lets get 6,7 from row 1 and column 1,2

array([6, 7])

In [232]:
array[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [233]:
# Iterating over an array

In [235]:
array= np.arange(1,10)

In [238]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [239]:
array_2d = np.arange(1,17).reshape(4,4)


In [240]:
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [258]:
print('with loop ->',end=' ')
for i in array_2d:
    for j in i:
        print(j,end=' ')
print()

# or  
print('with convert 2d into 1d ->',end=' ')
for val in array_2d.flatten():
    print(val,end=' ')

with loop -> 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 
with convert 2d into 1d -> 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [259]:
# numpy method to iter over ndim array

In [ ]:
# for 2d numpy array
for i in np.nditer(array_2d):
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [268]:
print(array_3d,end='\n\n')
# for 3d numpy array
for i in np.nditer(array_3d):
    print(i,end=' ')

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

1 2 3 4 5 6 7 8 

In [ ]:
# Stacking and Spitting concept --> condition --> size of the arrays must be the same

In [273]:
#stacking : Joining the arrays together
    # vertical --> joining two matrices column by column ->vstack()
    # horizontal  --> joining two table or matrices  row by row -> hstack()

In [297]:
print(arr_1,end='\n\n')
print(arr_2)
horizontal_array = np.hstack((arr_1,arr_2))
print('\nHorizontal Array:\n',horizontal_array)

vertical_array = np.vstack((arr_1,arr_2))
print('\nVertical Array:\n',vertical_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

Horizontal Array:
 [[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]

Vertical Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [298]:
# splitting -->  
    # horizontal splitting --> np.hsplit(array, number of parts you want your array to be splitter at)
    # vertical splitting --> np.vsplit(array, no. of parts)

In [299]:

horizontal_split = np.hsplit(horizontal_array,2)


In [300]:
horizontal_split

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
vertical_split = np.vsplit(vertical_array,4)

In [302]:
vertical_split

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [340]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
np.ndim(a)
print(a)
print(b)
print(a+b)


[[1]
 [2]
 [3]]
[10 20 30]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [335]:
arr = np.array([1,2,3])
arr + 10

array([11, 12, 13])

In [356]:
print(arr)
np.argmax(arr)
np.argmin(arr)

[1 2 3 4]


np.int64(0)

In [367]:
# sort 
arr= np.random.randint((4,4))
np.sort(arr)

array([0, 0], dtype=int32)

In [361]:
# unique
np.unique(arr)

array([1, 2, 3, 4])